name: Main Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Maple
      uses: actions/checkout@v3
      with:
        path: Maple

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: dotnet build -c Release Maple/Source/Maple.sln
